from dotenv import load_dotenv
import os

load_dotenv()

command_file = open(os.getenv("COMMAND_PATH"), "r")

WEBSOCKET_URL = os.getenv("WEBSOCKET_URL")
ACCESS_TOKEN = os.getenv("ACCESS_TOKEN")
DEVICE_ESTIMATED_LATENCY_SECONDS = float(os.getenv("DEVICE_ESTIMATED_LATENCY_SECONDS"))

COMMAND_TEMPLATE = "".join(command_file.readlines())

RED_PERCIEVED_BRIGHTNESS_FACTOR = float(os.getenv("RED_PERCIEVED_BRIGHTNESS_FACTOR"))
GREEN_PERCIEVED_BRIGHTNESS_FACTOR = float(os.getenv("GREEN_PERCIEVED_BRIGHTNESS_FACTOR"))
BLUE_PERCIEVED_BRIGHTNESS_FACTOR = float(os.getenv("BLUE_PERCIEVED_BRIGHTNESS_FACTOR"))

BASE_BRIGHTNESS = float(os.getenv("BASE_BRIGHTNESS"))
BRIGHTNESS_VARIATION_SQRT_FACTOR = float(os.getenv("BRIGHTNESS_VARIATION_SQRT_FACTOR"))
BRIGHTNESS_VARIATION_FACTOR = float(os.getenv("BRIGHTNESS_VARIATION_FACTOR"))

FORCED_VALUE_CHANNEL = float(os.getenv("FORCED_VALUE_CHANNEL"))

MAX_DEVICE_BRIGHTNESS = float(os.getenv("MAX_DEVICE_BRIGHTNESS"))

HUE_TRANSITION_SPEED_PERCENT_PER_SECOND = float(os.getenv("HUE_TRANSITION_SPEED_PERCENT_PER_SECOND")) / 100 * 180
SATURATION_TRANSITION_SPEED_PERCENT_PER_SECOND = float(os.getenv("SATURATION_TRANSITION_SPEED_PERCENT_PER_SECOND")) / 100 * 100
BRIGHTNESS_TRANSITION_SPEED_PERCENT_PER_SECOND = float(os.getenv("BRIGHTNESS_TRANSITION_SPEED_PERCENT_PER_SECOND")) / 100 * MAX_DEVICE_BRIGHTNESS

WAIT_SECONDS_AFTER_COMMAND = float(os.getenv("WAIT_SECONDS_AFTER_COMMAND"))

MINIMUM_HUE_CHANGE_TO_TRIGGER_TRANSITION = float(os.getenv("MINIMUM_HUE_CHANGE_TO_TRIGGER_TRANSITION"))
MINIMUM_SATURATION_CHANGE_TO_TRIGGER_TRANSITION = float(os.getenv("MINIMUM_SATURATION_CHANGE_TO_TRIGGER_TRANSITION"))

command_file.close()